name: Python Quality Check and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "agscaps"
        use-pylint: true
        use-flake8: true
        use-black: true
        use-mypy: true
